/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hcd_common_TgtAdminJNI */

#ifndef _Included_com_hcd_common_TgtAdminJNI
#define _Included_com_hcd_common_TgtAdminJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hcd_common_TgtAdminJNI
 * Method:    execute
 * Signature: ([Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_hcd_common_TgtAdminJNI_execute
  (JNIEnv *, jobject, jobjectArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
